name: 'Sub issue'
description: Issues específicos que nacen de un issue muy grande

body:
  - type: textarea
    id: description
    attributes:
      label: Descripción
    validations:
      required: true
