name: DEPLOY DEV

permissions:
  contents: write

on:
  push:
    branches:
      - "dev"
    paths-ignore:
      - "**.mdx"
      - "**.md"
      - "**.stories.*"
      - ".storybook/"

jobs:
  deploy-dev:
    environment: dev
    env:
      VITE_API_URL: ${{ vars.API_URL }}
      BASE_URL: ${{ vars.BASE_URL }}
      VITE_IS_HASH: ${{ vars.VITE_IS_HASH }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8


      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm

    
      - name: Build
        run: |
          pnpm install
          pnpm build
          touch dist/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist

  